### ISSUE TITLE
Invalid config

### ISSUE THREAD

**Issue by chex01** [alryaz/hass-tns-energo#3]
После обновления до 0.0.5 вылетает ошибка:
```
Setup failed for tns_energo: Unable to import component: No module named 'inter_rao_energosbyt'
```

**Comment by ananyevgv** [comment]
При установке выдает ошибку  ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration tns_energo: No module named 'inter_rao_energosbyt'

**Comment by alryaz** [comment]
В API, используемом компонентом, был допущен лишний импорт другого АПИ.

Релиз снят с GitHub, сейчас будет новый.

**Comment by chex01** [comment]
После установки версии 0.0.6 Home Assistant отказывается перезагружаться.
Выводится сообщение:
![Screenshot_20210924-144237_Home_Assistant.png](https://user-images.githubusercontent.com/12098416/134668902-bcadce20-b86d-4f57-ab88-026dbbbf8b0e.png)

**Comment by alryaz** [comment]
@chex01 полагаю, что HA использует старую версию библиотеки.

Попробуйте удалить компонент, и установить его снова.
