### ISSUE TITLE
Лишний "-" у объекта

### ISSUE THREAD

**Issue by chex01** [alryaz/hass-tns-energo#5]
У объекта sensor.tns_nn_хххххххххххх_account при значении '0,0 руб.' появляется знак '-'.
![Screenshot_20210924-144815_Home_Assistant.png](https://user-images.githubusercontent.com/12098416/134670019-00624e63-16e2-4ad6-9692-bdb523edaf96.png)

**Comment by alryaz** [comment]
В `main` выпущен коммит, исправляющий данное замечание. Спасибо, что сообщили!
